/**
 * Regenerates public/fonts/ from Google Fonts: keeps only the `latin` and
 * `latin-ext` subsets (enough for ES/EN) and rewrites the `src` URLs to point
 * at same-origin files. Variable families (Space Grotesk, IBM Plex Sans) ship
 * one file reused across weights; IBM Plex Mono ships one per weight. Files are
 * named by a content hash so identical payloads are stored once.
 *
 *   node scripts/vendor-fonts.mjs
 */
import { mkdir, writeFile, readdir, rm } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap';
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const OUT = path.resolve('public/fonts');
const KEEP = new Set(['latin', 'latin-ext']);

const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then((r) => r.text());
await mkdir(OUT, { recursive: true });
for (const f of await readdir(OUT).catch(() => [])) if (f.endsWith('.woff2') || f === 'fonts.css') await rm(path.join(OUT, f));

// One `/* subset */` comment immediately precedes each @font-face rule.
const faceRe = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
const faces = [];
const urls = new Map(); // remote url -> { family, subset }
for (const [, subset, face] of css.matchAll(faceRe)) {
  if (!KEEP.has(subset)) continue;
  const url = face.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  if (!url) continue;
  const family = face.match(/font-family:\s*'([^']+)'/)?.[1].replace(/\s+/g, '') ?? 'font';
  urls.set(url, { family, subset });
  faces.push({ url, face });
}

const localName = new Map(); // remote url -> local filename
await Promise.all(
  [...urls].map(async ([url, { family, subset }]) => {
    const buf = Buffer.from(await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()));
    const hash = createHash('sha256').update(buf).digest('hex').slice(0, 8);
    const name = `${family}-${subset}-${hash}.woff2`;
    await writeFile(path.join(OUT, name), buf);
    localName.set(url, name);
    console.log(`  ${name}  ${(buf.length / 1024).toFixed(1)} KB`);
  }),
);

let out = `/* Generated by scripts/vendor-fonts.mjs — do not edit. Latin + latin-ext subsets only. */\n`;
for (const { url, face } of faces) {
  out += face.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url(/fonts/${localName.get(url)})`).trim() + '\n';
}
await writeFile(path.join(OUT, 'fonts.css'), out);

const unique = new Set(localName.values());
console.log(`\n${unique.size} unique files, ${faces.length} @font-face rules, fonts.css ${(Buffer.byteLength(out) / 1024).toFixed(1)} KB`);
